// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DevolverImagenReconocimiento() {
  return window['go']['main']['App']['DevolverImagenReconocimiento']();
}

export function DevolverImagenesExploradas() {
  return window['go']['main']['App']['DevolverImagenesExploradas']();
}

export function DevolverResultadoProcesamiento(arg1, arg2) {
  return window['go']['main']['App']['DevolverResultadoProcesamiento'](arg1, arg2);
}
