// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {explorar} from '../models';
import {procesar} from '../models';

export function DevolverImagenReconocimiento():Promise<string>;

export function DevolverImagenesExploradas():Promise<explorar.ImagenesExploradas>;

export function DevolverResultadoProcesamiento(arg1:string,arg2:Array<string>):Promise<procesar.RespuestaProcesamiento>;
